---
- name: Web Server
  hosts: terraform

  tasks:
    - name: Update Packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        name: "*"
        state: latest

    - name: Install La_p
      become: true
      ansible.builtin.apt:
        name:
          - apache2
          - php
          - php-mysql
          - libapache2-mod-php
        state: latest

    - name: Remove default site content
      become: true
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: Download and extract Wordpress
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/
        mode: 0755
        extra_opts:
          - --strip-components=1

    - name: Creating Wordpress config
      become: true
      ansible.builtin.copy:
        remote_src: true
        src: /var/www/html/wp-config-sample.php
        dest: /var/www/html/wp-config.php
        mode: 0644
        force: false

    - name: Configure Wordpress
      become: true
      ansible.builtin.replace:
        path: /var/www/html/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - regexp: username_here
          replace: "{{ wordpress_db_username }}"
        - regexp: password_here
          replace: "{{ wordpress_db_password }}"
        - regexp: localhost
          replace: "{{ wordpress_db_host }}"
        - regexp: database_name_here
          replace: "{{ wordpress_db_name }}"
      loop_control:
        label: "{{ item.regexp }}"
